#!/bin/bash

# ANSI colors
export RED="\033[31m"
export GRN="\033[32m"
export YEL="\033[33m"
export BLU="\033[34m"
export NOC="\033[0m"

main() {
	validate
	configure
	packages
	unixuser
	dotfiles
}

packages() {
	header "packages"
	pacman -Syyu --needed --noconfirm curl vim bash-completion \
		git tree file htop neofetch tmux sudo net-tools
}

configure() {
	header "configure"
	if grep '#' /etc/locale.gen ; then
		echo 'en_GB.UTF-8 UTF-8' > /etc/locale.gen
		locale-gen
	fi
	if ! grep vim /etc/environment ; then
		echo 'EDITOR=vim' >> /etc/environment
		echo 'LC_ALL=en_GB.UTF-8' >> /etc/environment
	fi
	if [ ! -f /etc/locale.conf ] ; then
		echo 'LANG=en_GB.UTF-8' > /etc/locale.conf
	fi
}

unixuser() {
	header "unix user"
	if ! id unix ; then
		useradd -m -s /bin/bash -G wheel unix
	else
		warn "user unix already set up"
	fi
	if [ ! -f /etc/sudoers.d/wheelnopass ] ; then
		echo 'unix ALL=(ALL) NOPASSWD: ALL' \
		| tee /etc/sudoers.d/unixnopass
	fi
}

validate() {
	[ -f /etc/arch-release ] || die "not arch linux"
	[ ${UID} -eq 0 ] || die "gotta be root"
}

dotfiles() {
	header "dot files"
	git clone https://github.com/lyderic/dotrun /dev/shm/dotrun
	for path in /dev/shm/dotrun/dotfiles/* ; do
		dotname=".$(basename ${path})"
		warn "${path} [${dotname}]"
		for destdir in /root /home/unix ; do
			cp -v "${path}" "${destdir}/${dotname}"
		done
	done
	for dotbashrc in /root/.bashrc /home/unix/.bashrc ; do
		[ -f "${dotbashrc}" ] || touch "${dotbashrc}"
		if ! grep bigbang "${dotbashrc}" ; then
			echo 'source $HOME/.bigbang' >> "${dotbashrc}"
		fi
	done
	chown -v unix: /home/unix/\.[a-z]*
	rm -rf /dev/shm/dotrun
}

die() {
	echo -e "${RED}${1}${NOC}"
	exit 67
}

warn() {
	echo -e "${YEL}${1}${NOC}"
}

header() {
	echo -e "${BLU}[${1}]${NOC}"
}

main ${@}
