#!/bin/bash

# ANSI colors
export RED="\033[31m"
export GRN="\033[32m"
export YEL="\033[33m"
export BLU="\033[34m"
export NOC="\033[0m"

DISTRO="unknown"
PACKAGES="bash curl vim bash-completion git tree file htop tmux sudo net-tools"

main() {
	DISTRO=$(grep -E '^ID=' /etc/*-release | sed -e 's/^.*ID=//')
	echo "Distribution: ${DISTRO}"
	validate
	case "${DISTRO}" in
		"ubuntu"|"debian")
			debian_packages
			unixuser
			dotfiles
		;;
		"arch")
			arch_configure
			arch_packages
			unixuser
			dotfiles
		;;
		"alpine")
			alpine_packages
			unixuser
			dotfiles
		;;
		*) die "${DISTRO}: unknown distribution" ;;
	esac
}

arch_packages() {
	PACKAGES="${PACKAGES} pacman-contrib"
	header "arch packages"
	sed -i -e 's/#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
	pacman -Syyu --needed --noconfirm ${PACKAGES}
}

debian_packages() {
	header "debian packages"
	apt update && apt -y upgrade
	apt -y install ${PACKAGES}
}

alpine_packages() {
	header "alpine packages"
	apk update && apk upgrade
	apk add ${PACKAGES}
}

arch_configure() {
	header "configure"
	if grep '#' /etc/locale.gen ; then
		echo 'en_GB.UTF-8 UTF-8' > /etc/locale.gen
		locale-gen
	fi
	if ! grep vim /etc/environment ; then
		echo 'EDITOR=vim' >> /etc/environment
		echo 'LC_ALL=en_GB.UTF-8' >> /etc/environment
	fi
	if [ ! -f /etc/locale.conf ] ; then
		echo 'LANG=en_GB.UTF-8' > /etc/locale.conf
	fi
}

unixuser() {
	header "unix user"
	if id unix ; then
		warn "user unix already set up"
		return
	fi
	if which useradd ; then
		useradd -m -s /bin/bash -G wheel unix
	elif which adduser ; then
		adduser -D -s /bin/bash unix
	else
		die "No useradd nor adduser command found!"
	fi
	unixsudo
}

unixsudo() {
	id unix || die "no 'unix' user found!"
	if [ ! -f /etc/sudoers.d/unixnopass ] ; then
		echo 'unix ALL=(ALL) NOPASSWD: ALL' \
		| tee /etc/sudoers.d/unixnopass
	fi
}

validate() {
	grep -q lyderic /etc/passwd && die "'lyderic' user detected"
	[ $(id -u) -eq 0 ] || die "gotta be root"
}

dotfiles() {
	header "dot files"
	git clone https://github.com/lyderic/dotrun /dev/shm/dotrun
	for path in /dev/shm/dotrun/dotfiles/* ; do
		dotname=".$(basename ${path})"
		warn "${path} [${dotname}]"
		for destdir in /root /home/unix ; do
			cp -v "${path}" "${destdir}/${dotname}"
		done
	done
	for dotbashrc in /root/.bashrc /home/unix/.bashrc ; do
		[ -f "${dotbashrc}" ] || touch "${dotbashrc}"
		if ! grep bigbang "${dotbashrc}" ; then
			echo 'source $HOME/.bigbang' >> "${dotbashrc}"
		fi
	done
	chown -v unix: /home/unix/\.[a-z]*
	rm -rf /dev/shm/dotrun
}

die() {
	echo -e "${RED}${1}${NOC}"
	exit 67
}

warn() {
	echo -e "${YEL}${1}${NOC}"
}

header() {
	echo -e "${BLU}[${1}]${NOC}"
}

main ${@}
