#!/bin/bash

# ANSI colors
export RED="\033[31m"
export GRN="\033[32m"
export YEL="\033[33m"
export BLU="\033[34m"
export NOC="\033[0m"

main() {
	validate
	packages
	configure
}

packages() {
	header "packages"
	pacman -Syyu --needed --noconfirm xorg-server noto-fonts xfce4 tigervnc xfce4-terminal firefox
}

configure() {
	header "configure"
	[ -d ~unix/.vnc ] || mkdir -v ~unix/.vnc
	echo ':0=unix' >> /etc/tigervnc/vncserver.users
	echo 'session=openbox' > ~unix/.vnc/config
	echo 'geometry=1920x1000' >> ~unix/.vnc/config
	echo coucou | vncpasswd -f > ~unix/.vnc/passwd
	chown -R unix: ~unix/.vnc
	chmod 0600 ~unix/.vnc/passwd
	systemctl enable vncserver@:0
	systemctl start vncserver@:0
}

validate() {
	[ -f /etc/arch-release ] || die "not arch linux"
	[ ${UID} -eq 0 ] || die "gotta be root"
}

die() {
	echo -e "${RED}${1}${NOC}"
	exit 67
}

warn() {
	echo -e "${YEL}${1}${NOC}"
}

header() {
	echo -e "${BLU}[${1}]${NOC}"
}

main ${@}
